force-app/main/default/objects/Case/fields/Is_Simply_Tasks_Case__c.field-meta.xml
<CustomField>
    <fullName>Is_Simply_Tasks_Case__c</fullName>
    <formula>NOT(ISBLANK(Task_Template__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Simply Tasks Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Task_Template_Step__c.field-meta.xml
<CustomField>
    <fullName>Task_Template_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/Task_Dependency__c.object-meta.xml
<CustomObject>
    <description>Houses dependencies between actual tasks.  Based on the templates, template steps, and template step dependencies.</description>
    <label>Task Dependency</label>
    <nameField>
        <label>Task Dependency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Dependency__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Task Dependencies</relationshipLabel>
    <relationshipName>Task_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/fields/Task_Depends_On_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Depends_On_Id__c</fullName>
    <label>Task Depends On Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/fields/Task_Template_Step__c.field-meta.xml
<CustomField>
    <fullName>Task_Template_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template Step</label>
    <referenceTo>Task_Template_Step_Dependency__c</referenceTo>
    <relationshipLabel>Task Dependencies</relationshipLabel>
    <relationshipName>Task_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Is_Master_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Master_Template__c</fullName>
    <formula>ISBLANK( Parent_Template__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Master Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>false</active>
    <description>Used to create a task on objects</description>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateProcessHelperTest.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
@IsTest
private class CreateProcessHelperTest {

    @IsTest
    private static void testCreateCases() {

        User adminUser = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);
        System.runAs(adminUser) {
            TestDataFactory.TestDataFactoryData testData = TestDataFactory.createAllTestData('Contact');

            List<Case> cases =
                [
                    SELECT Id
                    FROM Case
                    WHERE Is_Simply_Tasks_Case__c = true
                ];

            Assert.areEqual(true, cases.isEmpty(), 'No cases to start');

            Task_Template__c masterTemplate =
                [
                    SELECT Id
                    FROM Task_Template__c
                    WHERE Is_Master_Template__c = true
                    LIMIT 1
                ];
                
            createCasesFromTemplateAndContact(masterTemplate.Id, testData.thisObject.Id);

            List<Task_Template_Step__c> steps =
                [
                    SELECT Id
                    FROM Task_Template_Step__c
                ];

            cases =
                [
                    SELECT Id
                    FROM Case
                    WHERE Is_Simply_Tasks_Case__c = true
                ];

            Assert.areEqual(false, cases.isEmpty(), 'Cases should have been created for the template');

            List<Task> tasks =
                [
                    SELECT Id
                    FROM Task
                    WHERE WhatId = :cases
                ];
            Assert.areEqual(false, tasks.isEmpty(), 'Tasks should have been created for the template steps.');

            List<Task_Dependency__c> dependencies =
                [
                    SELECT Id, Task_Id__c, Task_Depends_On_Id__c
                    FROM Task_Dependency__c
                    WHERE Case__c = :cases
                ];
            System.assertNotEquals(true, dependencies.isEmpty(), 'There should be dependencies amongst the tasks');
        }

    }

    @TestVisible
    private static void createCasesFromTemplateAndContact(Id masterTemplateId, Id contactId) {

        CreateProcessHelper.CreateCaseRequest request = new CreateProcessHelper.CreateCaseRequest();
        request.objectApiName = 'Contact';
        request.objectId = contactId;
        request.templateId = masterTemplateId;

        User adminUser = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);
        System.runAs(adminUser) {
            CreateProcessHelper processHelper = new CreateProcessHelper(request);
            processHelper.createCases();
        }
    }

}