force-app/main/default/objects/Case/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>The depth of this case to the master case.  Used to calculate the number of tasks and tasks completed.</description>
    <label>Level</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>The level depth of this case relative to the master template.</description>
    <label>Level</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TemplateHelperTest.cls
/**
 * @description       : 
 * @author            : Brian Ezell (SImplyEZ)
 * @group             : 
 * @last modified on  : 07-15-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
@IsTest
private class TemplateHelperTest {

    @IsTest
    private static void testUpdateTemplateLevelCounts() {

        User admin = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);
        System.runAs(admin) {
            
            TestDataFactory.TestDataFactoryData testData = TestDataFactory.createAllTestData('Contact');

            //Get the lowest level so far
            Task_Template__c temp = 
                [
                    SELECT Id, Level__c, Master_Task_Template__c
                    FROM Task_Template__c
                    ORDER BY Level__c DESC
                    LIMIT 1
                ];

            //Create a child case under this to insure it gets the correct level.
            Task_Template__c newTemplate = new Task_Template__c (
                Master_Task_Template__c = temp.Master_Task_Template__c,
                Parent_Template__c = temp.Id,
                Name = 'Next Level Child'
            );

            insert as user newTemplate;
            
            Task_Template__c retriveChild = 
                [
                    SELECT Id, Level__c, Master_Task_Template__c
                    FROM Task_Template__c
                    WHERE Id = :newTemplate.Id
                    LIMIT 1
                ];

            System.debug('Child = ' + retriveChild);

            Assert.areEqual(temp.Level__c+1, retriveChild.Level__c, 'This template should be at the next level from the parent.');

        }

    }

}