force-app/main/default/objects/Case/fields/Number_of_Tasks_To_Complete__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tasks_To_Complete__c</fullName>
    <label>Number of Tasks To Complete</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Task_Template_Step__c.field-meta.xml
<CustomField>
    <fullName>Task_Template_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EventTriggerControllerTest.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
@IsTest
private class EventTriggerControllerTest {
 
    @IsTest
    private static void testUpdateCase() {

        User adminUser = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);
        System.runAs(adminUser) {

            TestDataFactory.TestDataFactoryData testData = TestDataFactory.createAllTestData('Contact');
            CreateProcessFlowControllerTest.createCasesFromTemplateAndContact(testData.thisTemplate.Id, testData.thisObject.Id);

            Task oneTask = 
                [
                    SELECT Id, WhatId, OwnerId, Task_Template_Step__c
                    FROM Task
                    WHERE Is_Simply_Tasks_Created__c = true
                    LIMIT 1
                ];

            Case caseBefore = 
                [
                    SELECT Id, ParentId, Number_of_Tasks_To_Complete__c
                    FROM Case
                    WHERE Id = :oneTask.WhatId
                ];

            Event evt = new Event(
                WhatId = oneTask.WhatId,
                ActivityDate = Date.today().addDays(-1),
                OwnerId = oneTask.OwnerId,
                Is_Simply_Tasks_Created__c = true,
                Subject = 'Test Subject',
                Task_Template_Step__c = oneTask.Task_Template_Step__c,
                Dependent_Tasks_To_Complete__c = 0,
                Type = 'Meeting',
                IsAllDayEvent = true
            );
            insert as user evt;

            Case caseAfter = 
                [
                    SELECT Id, ParentId, Number_of_Tasks_To_Complete__c
                    FROM Case
                    WHERE Id = :oneTask.WhatId
                ];

            Assert.isTrue(caseAfter.Number_of_Tasks_To_Complete__c > 0, 'Case should have been updated');
        }
    }

}