force-app/main/default/objects/Case/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Is_Master_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Master_Template__c</fullName>
    <formula>ISBLANK( Parent_Template__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Master Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Templated_Objects__c.field-meta.xml
<CustomField>
    <fullName>Templated_Objects__c</fullName>
    <inlineHelpText>A list of objects that this template can be used with.  If custom objects are desired, their API name will need to be added to the picklist values.</inlineHelpText>
    <label>Templated Objects</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateObjectTemplateController.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
public with sharing class CreateObjectTemplateController {

    /**
    * @description Gets a list of templates for the given object name
    * @author Brian Ezell (Simply EZ) | 05-21-2024 
    * @param objectApiName 
    * @return string 
    **/
    @AuraEnabled
    public static string getTemplates(String objectApiName) {
        try {
            if(String.isBlank(objectApiName)) {
                throw new AuraHandledException('Object name cannot be blank.');
            }

            List<Task_Template__c> templates = 
                [
                    SELECT Id, Name
                    FROM Task_Template__c
                    WHERE Is_Master_Template__c = true
                        AND Is_Active__c = true
                        //AND Templated_Objects__c INCLUDES (:objectApiName)
                    WITH USER_MODE
                    ORDER BY Name DESC
                ];
            return JSON.serialize(templates);
        } catch (Exception e) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(e));
        }
    }

    /**
    * @description Takes in a request to create
    *   a new case(s) from a master template.
    * @author Brian Ezell (Simply EZ) | 05-21-2024 
    * @param request 
    * @return string 
    **/
    @AuraEnabled
    public static string createTemplate(String request) {
        try {
            CreateTemplateRequest templateRequest = (CreateTemplateRequest)JSON.deserialize(request, CreateTemplateRequest.class);
            CreateProcessFlowController.ProcessInput inputs = new CreateProcessFlowController.ProcessInput();
            inputs.ObjectId = templateRequest.objectId;
            inputs.ObjectName = templateRequest.objectName;
            inputs.TemplateId = templateRequest.templateId;

            CreateTemplateResponse response = new CreateTemplateResponse();
            List<Id> idList = CreateProcessFlowController.CreateProcess(new List<CreateProcessFlowController.ProcessInput> { inputs });

            if(idList != null && idList.size() > 0) {
                response.caseId = idList[0];
            }
            return JSON.serialize(response);
        } catch (Exception e) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(e));
        }
    }

    public class CreateTemplateRequest {
        public String objectId;
        public String objectName;
        public String templateId;
    }

    public class CreateTemplateResponse {
        public String caseId;
    }

}