force-app/main/default/objects/Case/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Task_Template_Step__c.field-meta.xml
<CustomField>
    <fullName>Task_Template_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step__c/fields/Parent_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Task_Template__c</fullName>
    <label>Parent Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Steps (Parent Task Template)</relationshipLabel>
    <relationshipName>Parent_Task_Template_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/Task_Template_Step_Dependency__c.object-meta.xml
<CustomObject>
    <label>Task Template Step Dependency</label>
    <nameField>
        <displayFormat>StepDependency-{0000}</displayFormat>
        <label>Task Template Step Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Template Step Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TemplateDeleteController.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 08-12-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
public with sharing class TemplateDeleteController {

    @AuraEnabled
    public static void deleteTemplate(String request) {
        try {
            
            DeleteTemplateRequest deleteRequest = (DeleteTemplateRequest) JSON.deserialize(request, DeleteTemplateRequest.class);

            //Find the master record
            Task_Template__c template =
                [
                    SELECT Id, Name, Master_Task_Template__c
                    FROM Task_Template__c
                    WHERE Id = :deleteRequest.templateId
                    WITH USER_MODE
                ];

            //See if any cases are associated with this template
            List<Case> cases =
                [
                    SELECT Id
                    FROM Case
                    WHERE Task_Template_Step__r.Parent_Task_Template__r.Master_Task_Template__c = :template.Master_Task_Template__c
                    WITH USER_MODE
                ];

            if(cases.size() > 0) {
                throw new AuraHandledException('Cannot delete template with (' + cases.size() + ') associated cases.');
            }

            List<Task_Template_Step_Dependency__c> deleteDependencies = 
            [
                SELECT Id
                FROM Task_Template_Step_Dependency__c
                WHERE Task_Template__r.Master_Task_Template__c = :template.Master_Task_Template__c
                WITH USER_MODE
            ];

            delete as user deleteDependencies;

            List<Task_Template_Step__c> deleteSteps = 
            [
                SELECT Id
                FROM Task_Template_Step__c
                WHERE Parent_Task_Template__r.Master_Task_Template__c = :template.Master_Task_Template__c
                WITH USER_MODE
            ];

            delete as user deleteSteps;

            List<Task_Template__c> deleteTemplates =
            [
                SELECT Id
                FROM Task_Template__c
                WHERE Master_Task_Template__c = :template.Master_Task_Template__c
                WITH USER_MODE
            ];

            delete as user deleteTemplates;
        } catch (Exception e) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(e));
        }
    }

    public class DeleteTemplateRequest {
        public String templateId;
    }

}