force-app/main/default/objects/Case/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Assigned_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Name__c</fullName>
    <description>Filled in by &quot;Assigned To&quot; flow to show who/what the template is assigned to.</description>
    <label>Assigned To Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Assigned_Type__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Type__c</fullName>
    <label>Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assign_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Assignee_Id__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Id__c</fullName>
    <description>The ID of the user, queue, etc that the user is assigned to.  This is handled by a lightning component.</description>
    <label>Assignee Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Assign_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Specific User</fullName>
    </customValue>
    <customValue>
        <fullName>Queue</fullName>
    </customValue>
    <customValue>
        <fullName>Person Creating</fullName>
    </customValue>
    <customValue>
        <fullName>Case Owner</fullName>
    </customValue>
    <description>For Simply Tasks.  Defines how the object gets assigned its owner.</description>
    <masterLabel>Assign Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AssignRecordOwnerControllerTest.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-23-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
@IsTest 
private class AssignRecordOwnerControllerTest {

    @IsTest
    private static void testGetAssignedOwnerOptionsQueue() {

        User u = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);

        Group queue = new Group (
            Name = 'Test Queue', 
            Type = 'Queue'
        );
        insert queue;

        System.runAs(u) {

            AssignRecordOwnerController.AssignRequest request = new AssignRecordOwnerController.AssignRequest();
            
            request.selectedId = queue.Id;
            request.assignType = 'Queue';


            String strRequest = JSON.serialize(request);

            String strResponse = AssignRecordOwnerController.getAssignedOwnerOptions(strRequest);
            AssignRecordOwnerController.AssignResponse response = (AssignRecordOwnerController.AssignResponse) JSON.deserialize(strResponse, AssignRecordOwnerController.AssignResponse.class);

            Assert.isNotNull(response, 'Expected response to not be null');
            Assert.isTrue(response.options.size() > 0, 'There should be options returned.');
        }
    }

    @IsTest
    private static void testGetAssignedOwnerOptionsSpecificUser() {

        User u = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.STANDARD_USER_PROFILE_NAME);

        AssignRecordOwnerController.AssignRequest request = new AssignRecordOwnerController.AssignRequest();

        request.selectedId = u.Id;
        request.assignType = 'Specific User';

        System.runAs(u) {

            String strRequest = JSON.serialize(request);

            String strResponse = AssignRecordOwnerController.getAssignedOwnerOptions(strRequest);
            AssignRecordOwnerController.AssignResponse response = (AssignRecordOwnerController.AssignResponse) JSON.deserialize(strResponse, AssignRecordOwnerController.AssignResponse.class);
 
            Assert.isNotNull(response, 'Expected response to not be null');
            Assert.isTrue(response.options.size() > 0, 'There should be options returned.');
        }

    }

    @IsTest
    private static void testGetAssignedOwnerOptionsOther() {

        AssignRecordOwnerController.AssignRequest request = new AssignRecordOwnerController.AssignRequest();

        request.assignType = 'Case Owner';

        String strRequest = JSON.serialize(request);

        User u = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.STANDARD_USER_PROFILE_NAME);

        System.runAs(u) {
            String strResponse = AssignRecordOwnerController.getAssignedOwnerOptions(strRequest);
            AssignRecordOwnerController.AssignResponse response = (AssignRecordOwnerController.AssignResponse) JSON.deserialize(strResponse, AssignRecordOwnerController.AssignResponse.class);

            Assert.isNotNull(response, 'Expected response to not be null');
            Assert.isTrue(response.options.size() == 0, 'There should be no options returned.');
        }
    }

    @IsTest
    private static void testUpdateObjectOwner() {

        User u = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);
        System.runAs(u) {

            TestDataFactory.TestDataFactoryData testData = TestDataFactory.createAllTestData('Contact');
            Group queue = new Group (
                Name = 'Test Queue', 
                Type = 'Queue'
            );
            insert queue;

            //Verify the Queue options
            AssignRecordOwnerController.UpdateAssignedOwnerRequest request = new AssignRecordOwnerController.UpdateAssignedOwnerRequest();
            request.recordId = testData.thisTemplate.Id;
            request.assignedType = 'Queue';
            request.assignedId = queue.Id;
            request.assignedOwnerName = queue.Name;

            String strRequest = JSON.serialize(request);    
            AssignRecordOwnerController.updateAssignedOwner(strRequest);

            Task_Template__c template = 
                [
                    SELECT Id, Assigned_Type__c, Assignee_Id__c, Assigned_To_Name__c
                    FROM Task_Template__c
                    WHERE Id = :testData.thisTemplate.Id
                ];

            Assert.isTrue(template.Assigned_Type__c.equalsIgnoreCase('Queue'), 'Assigned_Type__c should be marked as "queue".');
            Assert.isTrue(template.Assignee_Id__c.equalsIgnoreCase(queue.Id), 'Assignee_Id__c should be marked as the queue id.');
            Assert.isNotNull(template.Assigned_To_Name__c, 'Assigned_To_Name__c should be marked as the queue name.');
        }
    }

    @IsTest
    private static void testGetAssignedOwner() {
     
        User u = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);

        System.runAs(u) {
            TestDataFactory.TestDataFactoryData testData = TestDataFactory.createAllTestData('Account');
            String strResponse = AssignRecordOwnerController.getAssignedOwner(testData.thisTemplate.Id);
            AssignRecordOwnerController.GetAssignOwnerResponse response = (AssignRecordOwnerController.GetAssignOwnerResponse) JSON.deserialize(strResponse, AssignRecordOwnerController.GetAssignOwnerResponse.class);
            
            Assert.isNotNull(response, 'Expected response to not be null');
        }

    }

}