force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ImportTemplateController.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
public with sharing class ImportTemplateController {

    @AuraEnabled
    public static String importTemplate(String request) {
        try {
            ImportTemplateRequest req = (ImportTemplateRequest) JSON.deserialize(request, ImportTemplateRequest.class);
            Id masterTemplateId = importTemplateFromRecord(req.importRequestId);
            ImportTemplateResponse response = new ImportTemplateResponse();
            response.masterTemplateId = masterTemplateId;
            return JSON.serialize(response);
        } catch (Exception ex) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(ex));
        }
    }

    /**
    * @description Get the content document files on this import request and
    *   create the templates.
    * @author Brian Ezell (Simply EZ) | 09-08-2024 
    * @param importRequestId 
    **/
    private static Id importTemplateFromRecord(String importRequestId) {

        ContentDocumentLink cdl = 
            [
                SELECT Id, LinkedEntityId, ContentDocumentId
                FROM ContentDocumentLink
                WHERE LinkedEntityId = :importRequestId
                WITH USER_MODE
                LIMIT 1
            ];

        Id documentId = cdl.ContentDocumentId;

        ContentVersion version = 
            [
                SELECT Id, ContentDocumentId, VersionData
                FROM ContentVersion
                WHERE ContentDocumentId = :documentId
                WITH USER_MODE
                LIMIT 1
            ];
        String jsonData = version.VersionData.toString();
        ImportTemplateHelper importHelper = new ImportTemplateHelper();

        Id masterTemplateId =  importHelper.importJsonTemplates(jsonData);
        Master_Task_Template__c masterTemplate = 
            [
                SELECT Id, Name, Task_Template__c
                FROM Master_Task_Template__c
                WHERE Id = :masterTemplateId
                WITH USER_MODE
            ];

        return masterTemplate.Task_Template__c;
    }   

    public class ImportTemplateRequest {
        public String importRequestId;
    }

    public class ImportTemplateResponse {
        public String masterTemplateId;
    }
    
}