force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/Task_Dependency__c.object-meta.xml
<CustomObject>
    <description>Houses dependencies between actual tasks.  Based on the templates, template steps, and template step dependencies.</description>
    <label>Task Dependency</label>
    <nameField>
        <label>Task Dependency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Dependency__c/fields/Task_Depends_On_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Depends_On_Id__c</fullName>
    <label>Task Depends On Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/fields/Task_Template_Step__c.field-meta.xml
<CustomField>
    <fullName>Task_Template_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template Step</label>
    <referenceTo>Task_Template_Step_Dependency__c</referenceTo>
    <relationshipLabel>Task Dependencies</relationshipLabel>
    <relationshipName>Task_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Templated_Object__c.field-meta.xml
<CustomField>
    <fullName>Templated_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the object that this template can be used.</description>
    <inlineHelpText>References the object that this template can be used.</inlineHelpText>
    <label>Templated Object</label>
    <referenceTo>Object__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>false</active>
    <description>Used to create a task on objects</description>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <defaultValue>&quot;Task&quot;</defaultValue>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Activity_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The order of the steps when displayed under the template.</inlineHelpText>
    <label>Order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Parent_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Task_Template__c</fullName>
    <label>Parent Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Steps (Parent Task Template)</relationshipLabel>
    <relationshipName>Parent_Task_Template_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/Task_Template_Step_Dependency__c.object-meta.xml
<CustomObject>
    <label>Task Template Step Dependency</label>
    <nameField>
        <displayFormat>StepDependency-{0000}</displayFormat>
        <label>Task Template Step Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Template Step Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Depends_On_Step__c.field-meta.xml
<CustomField>
    <fullName>Depends_On_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Depends On Step</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Task_Template_Step__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Step__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies (Depends On Step)</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Activity_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Task</fullName>
        <default>true</default>
        <label>Task</label>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <description>For Simply Tasks - used to determine the type of the activity.</description>
    <masterLabel>Activity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
@IsTest
public with sharing class TestDataFactory {

    public static final List<String> SIMPLY_TASKS_ADMIN_PERMISSION_SET = new List<String> { 'Simply_Tasks_Administrator' };
    public static final List<String> SIMPLY_TASKS_USER_PERMISSION_SET = new List<String> { 'Simply_Tasks_User' };

    public static User createUserWithPermissionSets(List<String> permissionSetList, String profile) {

        String userProfile = String.isBlank(profile) ? 
            Constants.STANDARD_USER_PROFILE_NAME :
            profile;
        Profile p = 
            [
                SELECT Id 
                FROM Profile 
                WHERE Name = :userProfile
            ]; 

        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String uid = h.SubString(0,8);
        String userName = uid + '@simply-tasks.com';

        User u = new User
            (
                Alias = 'standt', 
                Email = 'thisisrandom@iamnowhererandomly.com', 
                EmailEncodingKey = 'UTF-8', 
                LastName = 'Testing', 
                LanguageLocaleKey = 'en_US', 
                LocaleSidKey = 'en_US', 
                ProfileId = p.Id, 
                TimeZoneSidKey = 'America/Los_Angeles', 
                UserName = userName
            );
        insert u;
        List<PermissionSet> permissionSets = 
            [
                SELECT Id
                FROM PermissionSet
                WHERE Name = :permissionSetList
            ];
        List<PermissionSetAssignment> permissionSetAssignments = new List<PermissionSetAssignment>();
        for(PermissionSet ps : permissionSets) {
            permissionSetAssignments.add(new permissionSetAssignment (
                PermissionSetId = ps.Id,
                AssigneeId = u.Id
            ));
        }
        if(permissionSetAssignments.size() > 0) {
            insert permissionSetAssignments;
        }
        return u;

    }

    public static TestDataFactoryData createAllTestData(String objectApiName) {
        TestDataFactoryData factoryData = new TestDataFactoryData();
        factoryData.thisTemplate = createAllTemplatesAndSteps();
        factoryData.thisObject = getSObject(objectApiName);
        //factoryData.thisTemplate.Templated_Object__c = objectApiName;
        return factoryData;
    }

    public static void createCaseFromTemplate(TestDataFactoryData testData) {
        CreateProcessHelper.CreateCaseRequest request = new CreateProcessHelper.CreateCaseRequest();
        request.templateId = testData.thisTemplate.Id;
        request.objectApiName = testData.thisObject.getSObjectType().getDescribe().getName();
        request.objectId = testData.thisObject.Id;
        CreateProcessHelper processHelper = new CreateProcessHelper(request);
        processHelper.createCases();
    }

    public static Integer completeSomeTasks() {

        //Need to avoid dependent tasks taht can't be completed yet.
        List<Task_Dependency__c> dependencies = 
            [
                SELECT Id, Task_Depends_On_Id__c, Task_Id__c
                FROM Task_Dependency__c
            ];

        Set<Id> excludeIds = new Set<Id>();
        for(Task_Dependency__c d : dependencies) {
            excludeIds.add(d.Task_Id__c);
        }

        List<Task> someTasks = 
            [
                SELECT Id, Subject, Status
                FROM Task
                WHERE Id NOT IN :excludeIds
            ];

        for(Task t : someTasks) {
            t.Status = Constants.TASK_COMPLETED_STATUS;
        }
        update someTasks;
        return someTasks.size();
    }

    private static Task_Template__c createAllTemplatesAndSteps() {
        Task_Template__c topLevelTemplate = createTopLevelTemplate();
        Master_Task_Template__c masterTemplate = new Master_Task_Template__c();
        masterTemplate.Task_Template__c = topLevelTemplate.Id;
        insert masterTemplate;

        topLevelTemplate.Master_Task_Template__c = masterTemplate.Id;
        update topLevelTemplate;

        List<Task_Template__c> childTemplates = createChildTemplates(masterTemplate.Id, topLevelTemplate.Id, 3);
        List<Task_Template_Step__c> steps = new List<Task_Template_Step__c>();
        Integer idx = 0;

        for(Task_Template__c t : childTemplates) {
            steps.addAll(createTemplateSteps(t, 5));
            idx++;
        }

        insert steps;

        List<Task_Template_Step_Dependency__c> depends = createTemplateStepDependencies(childTemplates, steps);
        insert depends;
        return topLevelTemplate;
    }

    private static SObject getSObject(String objectApiName) {
        SObject so = SObjectData.makeObject(objectApiName);
        insert so;
        return so;
    }

    private static Task_Template__c createTopLevelTemplate() {
        Task_Template__c topLevelTemplate = new Task_Template__c (
            Is_Active__c = true,
            Name = 'Top Level Test Template'
        );
        insert topLevelTemplate;
        return topLevelTemplate;
    }


    /**
    * @description Creates the child templates.
    * @author Brian Ezell (Simply EZ) | 07-31-2024 
    * @param masterTemplate 
    * @param numberOfTemplates 
    * @return List<Task_Template__c> 
    **/
    private static List<Task_Template__c> createChildTemplates(Id masterTemplateId, Id topLevelTemplateId, Integer numberOfTemplates) {
        List<Task_Template__c> childTemplates = new List<Task_Template__c>();

        for(Integer i = 0; i < numberOfTemplates; i++) {
            childTemplates.add(new Task_Template__c (
                Is_Active__c = true,
                Name = 'Child Test Template ' + string.valueOf(i),
                Parent_Template__c = topLevelTemplateId,
                Master_Task_Template__c = masterTemplateId
            ));
        }

        insert childTemplates;
        return childTemplates;
    }

    /**
    * @description Creates the template steps.
    * @author Brian Ezell (Simply EZ) | 07-31-2024 
    * @param template 
    * @param numberOfSteps 
    * @return List<Task_Template_Step__c> 
    **/
    private static List<Task_Template_Step__c> createTemplateSteps(Task_Template__c template, Integer numberOfSteps) {
        List<Task_Template_Step__c> steps = new List<Task_Template_Step__c>();
        for(Integer i = 0; i < numberOfSteps; i++) {
            steps.add(new Task_Template_Step__c(
                Parent_Task_Template__c = template.Id,
                Order__c = i,
                Name = template.Name + ' ' + String.valueOf(i),
                Activity_Type__c = i == numberOfSteps - 1 ? 'Event' : 'Task'
                //Math.MOD(i, 2) == 0 ? 'Task' : 'Event'
            ));
        }
        return steps;
    }

    private static List<Task_Template_Step_Dependency__c> createTemplateStepDependencies(
        List<Task_Template__c> templateList, 
        List<Task_Template_Step__c> stepList) {

        List<Task_Template_Step_Dependency__c> depends = new List<Task_Template_Step_Dependency__c>();
        List<Task_Template_Step__c> justTasks = new List<Task_Template_Step__c>();

        for(Task_Template_Step__c step : stepList) {
            if(step.Activity_Type__c == 'Task') {
                justTasks.add(step);
            }
        }

        Task_Template_Step__c mainStep = justTasks[0];
        for(Task_Template__c t : templateList) {
            Integer currentIndex = 0;
            Integer maxIndex = justTasks.size() - 2;
            for(Task_Template_Step__c step : justTasks) {
                if(step.Parent_Task_Template__c == t.Id && step.Id != mainStep.Id) {
                    depends.add( 
                        new Task_Template_Step_Dependency__c (
                            Step__c = step.Id,
                            Depends_On_Step__c = mainStep.Id,
                            Task_Template__c = t.Id
                        )
                    );
                    currentIndex++;
                    if(currentIndex >= maxIndex) {
                        break;
                    }
                }
            }
        }
        
        return depends;
    }

    public class TestDataFactoryData {
        public TestDataFactoryData() {
            thisTemplate = null;
            thisObject = null;
        }

        public Task_Template__c thisTemplate;
        public SObject thisObject;

        public String getSObjectName() {
            return this.thisObject.getSObjectType().getDescribe().getName();
        }
    }
}