force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>The level depth of this case relative to the master template.</description>
    <label>Level</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template_Export__c/Template_Export__c.object-meta.xml
<CustomObject>
    <label>Template Export</label>
    <nameField>
        <displayFormat>EXP-{0000}</displayFormat>
        <label>Template Export Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Export__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Task Template</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This must be the top level template.</errorMessage>
        <filterItems>
            <field>Task_Template__c.Is_Master_Template__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Task_Template__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Template Exports</relationshipLabel>
    <relationshipName>Template_Exports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExportTemplateController.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 08-12-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
public with sharing class ExportTemplateController {

    /**
    * @description Exports the template as a file attached to the Export Template object.
    * @author Brian Ezell (Simply EZ) | 09-07-2024 
    * @param request 
    **/
    @AuraEnabled
    public static String exportTemplate(String request) {
        try {
            ExportTemplateRequest expRequest = (ExportTemplateRequest)JSON.deserialize(request, ExportTemplateRequest.class);

            Template_Export__c expTemplate = new Template_Export__c(
                Task_Template__c = expRequest.templateId
            );

            insert as user expTemplate;
                
            generateContent(expTemplate.Id, expRequest.templateId);

            ExportTemplateResponse response = new ExportTemplateResponse();
            response.exportTemplateId = expTemplate.Id;
            return JSON.serialize(response);

        } catch(Exception ex) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(ex));
        }
    }

    /**
    * @description Creates the json files from the template and saves it to a 
    *   JSON file attached to the export template.
    * @author Brian Ezell (Simply EZ) | 09-07-2024 
    * @param exportTemplateId 
    * @param templateId 
    **/
    private static void generateContent(String exportTemplateId, String templateId) {

        List<Task_Template__c> templates = CommonFunctions.getAllTemplates(templateId);

        String fileName = null;

        Master_Task_Template__c masterTemplate = 
            [
                SELECT Id, Name,
                    (
                        SELECT Id, Level__c, Name
                        FROM Task_Templates__r
                        WHERE Level__c = 0
                    )
                FROM Master_Task_Template__c
                WHERE Id = :templates[0].Master_Task_Template__c
                WITH USER_MODE
            ];

            fileName = String.format('{0}_{1}.json',
                new List<Object> {
                    masterTemplate.Task_Templates__r[0].Name,
                    DateTime.now()
                }
            );
        Blob templateBlob = Blob.valueOf(JSON.serialize(templates));
        CommonFunctions.createObjectDocument(exportTemplateId, fileName, templateBlob);
    }

    public class ExportTemplateRequest {
        public String templateId;
    }

    public class ExportTemplateResponse {
        public String exportTemplateId;
    }
    
}