force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CloneTemplateController.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/

public with sharing class CloneTemplateController {

    @AuraEnabled
    public static string cloneTemplate(String request) {
        try {
            CloneTemplateRequest cloneRequest = (CloneTemplateRequest) JSON.deserialize(request, CloneTemplateRequest.class);
            CloneAllTemplates clone = new CloneAllTemplates(cloneRequest.templateId);

            CloneTemplateResponse response = new CloneTemplateResponse();
            response.newTemplateId = clone.cloneTemplate(cloneRequest.newName);
            return JSON.serialize(response);
        } catch (Exception ex) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(ex));
        }
    }

    @AuraEnabled
    public static string getTemplate(String templateId) {
        try {

            if(String.isBlank(templateId)) {
                throw new AuraHandledException('Template id cannot be blank.');
            }

            Task_Template__c currentTemplate = 
                [
                    SELECT Id, Master_Task_Template__c,
                        Master_Task_Template__r.Task_Template__c
                    FROM Task_Template__c
                    WHERE Id = :templateId
                    WITH USER_MODE
                ];

            Task_Template__c topLevelTemplate = 
                [
                    SELECT Id, Name
                    FROM Task_Template__c
                    WHERE Id = :currentTemplate.Master_Task_Template__r.Task_Template__c
                    WITH USER_MODE
                ];
            return JSON.serialize(topLevelTemplate);
        } catch (Exception ex) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(ex));
        }
    }

    public class CloneTemplateRequest {
        public String templateId;
        public String newName;
    }

    public class CloneTemplateResponse {
        public String newTemplateId;
    }

}