force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Assigned_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Name__c</fullName>
    <description>Filled in by &quot;Assigned To&quot; flow to show who/what the template is assigned to.</description>
    <label>Assigned To Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Number_of_Child_Steps__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Child_Steps__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Child Steps</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Number_Of_Child_Template_Steps__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Child_Template_Steps__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Child Template Steps</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Templated_Object__c.field-meta.xml
<CustomField>
    <fullName>Templated_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the object that this template can be used.</description>
    <inlineHelpText>References the object that this template can be used.</inlineHelpText>
    <label>Templated Object</label>
    <referenceTo>Object__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A description of the template step.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Parent_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Task_Template__c</fullName>
    <label>Parent Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Steps (Parent Task Template)</relationshipLabel>
    <relationshipName>Parent_Task_Template_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/Task_Template_Step_Dependency__c.object-meta.xml
<CustomObject>
    <label>Task Template Step Dependency</label>
    <nameField>
        <displayFormat>StepDependency-{0000}</displayFormat>
        <label>Task Template Step Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Template Step Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Depends_On_Step__c.field-meta.xml
<CustomField>
    <fullName>Depends_On_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Depends On Step</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Task_Template_Step__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Step__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies (Depends On Step)</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TemplateBuilderController.cls
/**
 * @description       : The controller used for building out templates on the Aura component
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 08-12-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
@RestResource(urlMapping='/Flow/*')
global with sharing class TemplateBuilderController {

    @HttpPost
    global static String flowDependencies(String id) {
        return getTemplateNodes(id);
    }

    @AuraEnabled
    public static string getTemplateNodes(String templateId) {

        try {
            if(String.isBlank(templateId)) {
                throw new TemplateBuilderControllerException('Template id cannot be blank.');
            }

            Set<Id> templateIdList = new Set<Id>();
            templateIdList.add(templateId);

            Map<Id, Task_Template__c> mapTemplateIdToTemplate = getAlltemplates(templateId);
            List<TaskTemplateNode> templateNodes = getTemplateNodesInternal(mapTemplateIdToTemplate, templateIdList);
            return Json.serialize(templateNodes);
        } catch (Exception ex) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(ex));
        }
    }

    @AuraEnabled
    public static void deleteTaskRecord(String recordId) {
        try {

            if(String.isBlank(recordId)) {
                throw new TemplateBuilderControllerException('Record id cannot be blank.');
            }

            List<Task_Template_Step__c> taskTemplateSteps =
            [
                SELECT Id
                FROM Task_Template_Step__c
                WHERE Id = :recordId
                WITH USER_MODE
            ];

            delete as user taskTemplateSteps;

        } catch (Exception e) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(e));
        }
    }

    @AuraEnabled
    public static void deleteTemplateRecord(String recordId) {
        try {

            if(String.isBlank(recordId)) {
                throw new TemplateBuilderControllerException('Record id cannot be blank.');
            }

            List<Task_Template__c> taskTemplate =
            [
                SELECT Id
                FROM Task_Template__c
                WHERE Id = :recordId
                WITH USER_MODE
            ];
            
            delete as user taskTemplate;
        } catch (Exception e) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(e));
        }
    }


    /**
    * @description Gets a complete map of all templates involved
    * @author Brian Ezell (Simply EZ) | 08-12-2024
    * @param templateId 
    * @return Map<Id, Task_Template__c> 
    **/
    private static Map<Id, Task_Template__c> getAlltemplates(String templateId) {

        Map<Id, Task_Template__c> templates = new Map<Id, Task_Template__c> (
            CommonFunctions.getAllTemplates(templateId)
        );

        return templates;
    }


    /**
    * @description Gets the template nodes
    * @author Brian Ezell (Simply EZ) | 05-31-2024 
    * @param templateIds 
    * @return List<TaskTemplateNode> 
    **/
    private static List<TaskTemplateNode> getTemplateNodesInternal(Map<Id, Task_Template__c> allTemplates, Set<Id> templateIds) {
        Map<Id, TaskTemplateNode> newTemplates = new Map<Id, TaskTemplateNode>();

        List<Task_Template__c> templates = new List<Task_Template__c>();

        for(Id tId : templateIds) {
            templates.add(allTemplates.get(tId));
        }

        Set<Id> templateStepIds = new Set<Id>();
        for(Task_Template__c t : templates) {
            TaskTemplateNode templateNode = new TaskTemplateNode();
            templateNode.id = t.Id;
            templateNode.objectId = t.Templated_Object__c;
            templateNode.name = t.Name;
            templateNode.assignedName = t.Assigned_To_Name__c;
            templateNode.parentId = t.Parent_Template__c;
            templateNode.topLevelId = t.Master_Task_Template__c;
            templateNode.numberOfChildSteps = t.Number_of_Child_Steps__c;
            templateNode.numberOfChildTemplateSteps = t.Number_Of_Child_Template_Steps__c;

            Map<Id, Task_Template__c> childTemplates = new Map<Id, Task_Template__c>(t.Task_Templates__r);

            templateNode.childTemplateList = getTemplateNodesInternal(allTemplates, childTemplates.keySet());
            templateNode.childStepList = getTemplateStepNodes(t.Parent_Task_Template_Steps__r);

            newTemplates.put(t.Id, templateNode);
        }

        return newTemplates.values();
    }

    /**
    * @description Gets a usable list of steps for the template builder
    * @author Brian Ezell (Simply EZ) | 08-12-2024 
    * @param steps 
    * @return List<TaskTemplateStepNode> 
    **/
    private static List<TaskTemplateStepNode> getTemplateStepNodes(List<Task_Template_Step__c> steps) {

        List<TaskTemplateStepNode> stepNodes = new List<TaskTemplateStepNode>();

        //Add each step to the return list
        for(Task_Template_Step__c s : steps) {
            TaskTemplateStepNode stepNode = new TaskTemplateStepNode();
            stepNode.Id = s.Id;
            stepNode.Name = s.Name;
            stepNode.assignedName = s.Assigned_To_Name__c;

            //Add each dependency to the step dependency list
            for(Task_Template_Step_Dependency__c d : s.Task_Template_Step_Dependencies__r) {
                TaskTemplateStepDependencyNode depNode = new TaskTemplateStepDependencyNode();
                depNode.stepName = d.Task_Template__r.Name;
                depNode.dependsOnName = d.Depends_On_Step__r.Name;
                depNode.description = d.Description__c;
                stepNode.dependencyList.add(depNode);
            }

            stepNodes.add(stepNode);
        }

        return stepNodes;
    }

    public class TaskTemplateNode {
        public TaskTemplateNode() {
            childTemplateList = new List<TaskTemplateNode>();
            childStepList = new List<TaskTemplateStepNode>();
            numberOfChildSteps = 0;
            numberOfChildTemplateSteps = 0;
        }

        public String id;
        public String name;
        public String objectId;
        public String parentId;
        public String topLevelId;
        public Decimal numberOfChildSteps;
        public Decimal numberOfChildTemplateSteps;
        public String assignedName;
        public List<TaskTemplateNode> childTemplateList;
        public List<TaskTemplateStepNode> childStepList;
    }

    public class TaskTemplateStepNode {

        public TaskTemplateStepNode() {
            DependencyList = new LIst<TaskTemplateStepDependencyNode>();
        }

        public String id;
        public String name;
        public String assignedName;
        public String objectId;
        public List<TaskTemplateStepDependencyNode> dependencyList;
    }

    public class TaskTemplateStepDependencyNode {
        public String stepName;
        public string dependsOnName;
        public String description;
    }

    public class TemplateBuilderControllerException extends Exception {}
}