force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TemplateTriggerControllerTest.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
@IsTest
private class TemplateTriggerControllerTest {

    @IsTest
    private static void testTrigger() {

        User adminUser = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);
        System.runAs(adminUser) {

            TestDataFactory.createAllTestData('Account');

            List<Task_Template__c> templates = 
                [
                    SELECT Id, Master_Task_Template__c
                    FROM Task_Template__c
                ];

            for(Task_Template__c t : templates) {
                Assert.isNotNull(t.Master_Task_Template__c, 'The top level template should not be null.');
            }
        }
    }

}