force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Assigned_Type__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Type__c</fullName>
    <label>Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assign_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>The level depth of this case relative to the master template.</description>
    <label>Level</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Templated_Name__c.field-meta.xml
<CustomField>
    <fullName>Templated_Name__c</fullName>
    <inlineHelpText>Allows templating names of cases/tasks.  Can include &quot;[Name]&quot; to insert the name of the targeted object.</inlineHelpText>
    <label>Templated Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Templated_Objects__c.field-meta.xml
<CustomField>
    <fullName>Templated_Objects__c</fullName>
    <inlineHelpText>A list of objects that this template can be used with.  If custom objects are desired, their API name will need to be added to the picklist values.</inlineHelpText>
    <label>Templated Objects</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <defaultValue>&quot;Task&quot;</defaultValue>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Activity_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Assigned_Type__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Type__c</fullName>
    <inlineHelpText>Who does this activity get assigned to upon creation?</inlineHelpText>
    <label>Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assign_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A description of the template step.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Duration_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Days__c</fullName>
    <label>Duration In Days</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The order of the steps when displayed under the template.</inlineHelpText>
    <label>Order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Parent_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Task_Template__c</fullName>
    <label>Parent Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Steps (Parent Task Template)</relationshipLabel>
    <relationshipName>Parent_Task_Template_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Templated_Name__c.field-meta.xml
<CustomField>
    <fullName>Templated_Name__c</fullName>
    <inlineHelpText>Used as a template for the task/event name.  Can include [Name] for object name and [StepOrder] for step order fields to be included in the activity name at creation.</inlineHelpText>
    <label>Templated Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/Task_Template_Step_Dependency__c.object-meta.xml
<CustomObject>
    <label>Task Template Step Dependency</label>
    <nameField>
        <displayFormat>StepDependency-{0000}</displayFormat>
        <label>Task Template Step Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Template Step Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Depends_On_Step__c.field-meta.xml
<CustomField>
    <fullName>Depends_On_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Depends On Step</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Task_Template_Step__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Step__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies (Depends On Step)</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Activity_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Task</fullName>
        <default>true</default>
        <label>Task</label>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <description>For Simply Tasks - used to determine the type of the activity.</description>
    <masterLabel>Activity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Assign_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Specific User</fullName>
    </customValue>
    <customValue>
        <fullName>Queue</fullName>
    </customValue>
    <customValue>
        <fullName>Person Creating</fullName>
    </customValue>
    <customValue>
        <fullName>Case Owner</fullName>
    </customValue>
    <description>For Simply Tasks.  Defines how the object gets assigned its owner.</description>
    <masterLabel>Assign Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ImportTemplateHelper.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 08-12-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
public with sharing class ImportTemplateHelper {

    private List<Task_Template__c> oldTemplates;
    private Master_Task_Template__c newMasterCase;

    //private Map<Id, Task_Template__c> mapTemplateIdToTemplate = new Map<Id, Task_Template__c>();
    private Map<Id, Task_Template__c> mapOldTemplateIdToNewTemplate = new Map<Id, Task_Template__c>();
    private Map<Id, Task_Template_Step__c> mapOldStepIdToNewStep = new Map<Id, Task_Template_Step__c>();
    private Map<Id, Task_Template_Step_Dependency__c> mapOldDependsIdToNewDependency = new Map<Id, Task_Template_Step_Dependency__c>();

    /**
    * @description Takes a JSON version of templates and imports them into the system.
    * @author Brian Ezell (Simply EZ) | 09-08-2024 
    * @param jsonTemplates 
    **/
    public Id importJsonTemplates(String jsonTemplates) {
        oldTemplates = (List<Task_Template__c>)JSON.deserialize(jsonTemplates, List<Task_Template__c>.class);
        newMasterCase = new Master_Task_Template__c();
        insert as user newMasterCase;

        insertTemplates();
        insertSteps();
        insertDependencies();

        return newMasterCase.Id;
    }

    /**
    * @description Creates the new templates
    * @author Brian Ezell (Simply EZ) | 09-08-2024 
    **/
    private void insertTemplates() {

        for(Task_Template__c t : oldTemplates) {
            Task_Template__c newTemp = new Task_Template__c (
                Name = t.Name,
                Master_Task_Template__c = newMasterCase.Id,
                Assigned_Type__c = t.Assigned_Type__c,
                Is_Active__c = true,
                //Templated_Objects__c = t.Templated_Objects__c,
                Level__c = t.Level__c
            );
            mapOldTemplateIdToNewTemplate.put(t.Id, newTemp);

            for(Task_Template_Step__c s : t.Parent_Task_Template_Steps__r) {
                Task_Template_Step__c newStep = new Task_Template_Step__c (
                    Name = s.Name,
                    Activity_Type__c = s.Activity_Type__c,
                    Assigned_Type__c = s.Assigned_Type__c,
                    Description__c = s.Description__c,
                    Duration_In_Days__c = s.Duration_In_Days__c,
                    Order__c = s.Order__c,
                    Templated_Name__c = s.Templated_Name__c
                );
                mapOldStepIdToNewStep.put(s.Id, newStep);
            }
        }

        insert as user mapOldTemplateIdToNewTemplate.values();

    }

    /**
    * @description Creates the new template steps
    * @author Brian Ezell (Simply EZ) | 09-08-2024 
    **/
    private void insertSteps() {
        for(Task_Template__c t : oldTemplates) {

            Task_Template__c newTemplate = mapOldTemplateIdToNewTemplate.get(t.Id);

            if(t.Parent_Template__c != null) {
                newTemplate.Parent_Template__c = mapOldTemplateIdToNewTemplate.get(t.Parent_Template__c).Id;
            }

            for(Task_Template_Step__c s : t.Parent_Task_Template_Steps__r) {
                Task_Template_Step__c newStep = new Task_Template_Step__c (
                    Name = s.Name,
                    Activity_Type__c = s.Activity_Type__c,
                    Assigned_Type__c = s.Assigned_Type__c,
                    Description__c = s.Description__c,
                    Duration_In_Days__c = s.Duration_In_Days__c,
                    Order__c = s.Order__c,
                    Templated_Name__c = s.Templated_Name__c,
                    Parent_Task_Template__c = newTemplate.Id
                );
                mapOldStepIdToNewStep.put(s.Id, newStep);
            }
        }
        
        update as user mapOldTemplateIdToNewTemplate.values();
    }

    private void insertDependencies() {
        List<Task_Template_Step_Dependency__c> dependencies = new List<Task_Template_Step_Dependency__c>();
        for(Task_Template__c t : oldTemplates) {
            Task_Template__c newTemplate = mapOldTemplateIdToNewTemplate.get(t.Id);

            for(Task_Template_Step_Dependency__c dep : t.Task_Template_Step_Dependencies__r) {
                Task_Template_Step_Dependency__c newDepends = new Task_Template_Step_Dependency__c (
                    Depends_On_Step__c = mapOldStepIdToNewStep.get(dep.Depends_On_Step__c).Id,
                    Step__c = mapOldStepIdToNewStep.get(dep.Step__c).Id,
                    Description__c = dep.Description__c,
                    Task_Template__c = mapOldTemplateIdToNewTemplate.get(dep.Task_Template__c).Id
                );
                dependencies.add(newDepends);
            }
        }

        insert as user dependencies;
    }
    
}