force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Assigned_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Name__c</fullName>
    <description>Filled in by &quot;Assigned To&quot; flow to show who/what the template is assigned to.</description>
    <label>Assigned To Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Assigned_Type__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Type__c</fullName>
    <label>Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assign_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Assignee_Id__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Id__c</fullName>
    <description>The ID of the user, queue, etc that the user is assigned to.  This is handled by a lightning component.</description>
    <label>Assignee Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <description>Replicates the case record types.</description>
    <label>Case Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PFL Install</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PFL Install</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Is_Master_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Master_Template__c</fullName>
    <formula>ISBLANK( Parent_Template__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Master Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>The level depth of this case relative to the master template.</description>
    <label>Level</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Master_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Master_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Task Template</label>
    <referenceTo>Master_Task_Template__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Record_Owner__c.field-meta.xml
<CustomField>
    <fullName>Record_Owner__c</fullName>
    <label>Record Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Specific User</fullName>
            </value>
            <value>
                <fullName>Object Owner</fullName>
            </value>
            <value>
                <fullName>Person Creating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Templated_Name__c.field-meta.xml
<CustomField>
    <fullName>Templated_Name__c</fullName>
    <inlineHelpText>Allows templating names of cases/tasks.  Can include &quot;[Name]&quot; to insert the name of the targeted object.</inlineHelpText>
    <label>Templated Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Templated_Object__c.field-meta.xml
<CustomField>
    <fullName>Templated_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the object that this template can be used.</description>
    <inlineHelpText>References the object that this template can be used.</inlineHelpText>
    <label>Templated Object</label>
    <referenceTo>Object__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <defaultValue>&quot;Task&quot;</defaultValue>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Activity_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Assigned_Type__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Type__c</fullName>
    <inlineHelpText>Who does this activity get assigned to upon creation?</inlineHelpText>
    <label>Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assign_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Assignee_Id__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Id__c</fullName>
    <description>The ID of the assigned user, queue, etc. that is used.  A lightning component fills this in.</description>
    <label>Assignee Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A description of the template step.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Duration_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Days__c</fullName>
    <label>Duration In Days</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The order of the steps when displayed under the template.</inlineHelpText>
    <label>Order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Parent_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Task_Template__c</fullName>
    <label>Parent Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Steps (Parent Task Template)</relationshipLabel>
    <relationshipName>Parent_Task_Template_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Template_Master__c.field-meta.xml
<CustomField>
    <fullName>Template_Master__c</fullName>
    <formula>CASESAFEID(Parent_Task_Template__r.Master_Task_Template__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Template Master</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Templated_Name__c.field-meta.xml
<CustomField>
    <fullName>Templated_Name__c</fullName>
    <inlineHelpText>Used as a template for the task/event name.  Can include [Name] for object name and [StepOrder] for step order fields to be included in the activity name at creation.</inlineHelpText>
    <label>Templated Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/Task_Template_Step_Dependency__c.object-meta.xml
<CustomObject>
    <label>Task Template Step Dependency</label>
    <nameField>
        <displayFormat>StepDependency-{0000}</displayFormat>
        <label>Task Template Step Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Template Step Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Depends_On_Step__c.field-meta.xml
<CustomField>
    <fullName>Depends_On_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Depends On Step</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Task_Template_Step__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Step__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies (Depends On Step)</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Activity_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Task</fullName>
        <default>true</default>
        <label>Task</label>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <description>For Simply Tasks - used to determine the type of the activity.</description>
    <masterLabel>Activity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Assign_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Specific User</fullName>
    </customValue>
    <customValue>
        <fullName>Queue</fullName>
    </customValue>
    <customValue>
        <fullName>Person Creating</fullName>
    </customValue>
    <customValue>
        <fullName>Case Owner</fullName>
    </customValue>
    <description>For Simply Tasks.  Defines how the object gets assigned its owner.</description>
    <masterLabel>Assign Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CloneAllTemplates.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 08-12-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
public with sharing class CloneAllTemplates {

    //Maps Ids for template, steps and dependencies
    private Map<Id, Task_Template__c> mapOldTemplateIdToNewTemplate = new Map<Id, Task_Template__c>();
    private Map<Id, Task_Template_Step__c> mapOldStepIdToNewStep = new Map<Id, Task_Template_Step__c>();
    private Map<Id, Task_Template_Step_Dependency__c> mapOldDependencyIdToNewDependency = new Map<Id, Task_Template_Step_Dependency__c>();

    private Map<Id, Task_Template__c> mapOldTemplateIdToOldTemplate = new Map<Id, Task_Template__c>();
    private List<Task_Template_Step__c> oldSteps = new List<Task_Template_Step__c>();
    private List<Task_Template_Step_Dependency__c> oldDependencies = new List<Task_Template_Step_Dependency__c>();
    private Master_Task_Template__c newMaster;

    private Task_Template__c oldTopLevelTemplate;
    private Task_Template__c newTopLevelTemplate;

    /**
    * @description Takes master template and the templates associated with it
    *   and create a clone with the new template name.
    * @author Brian Ezell (Simply EZ) | 07-08-2024 
    * @param templateId 
    **/
    public CloneAllTemplates(String templateId) {

        if(String.isBlank(templateId)) {
            throw new DmlException('You must provide a template id.');
        }

        loadTemplateData(templateId);
        
    }

    /**
    * @description Creates the cloned templates and returns the top level new template id
    * @author Brian Ezell (Simply EZ) | 06-01-2024 
    * @return Id 
    **/
    public Id cloneTemplate(String newName) {

        //Create the new templates and link them.
        createTemplates(newName);

        //Update the master with the new top level template.
        newTopLevelTemplate = mapOldTemplateIdToNewTemplate.get(oldTopLevelTemplate.Id);
        newMaster.Task_Template__c = mapOldTemplateIdToNewTemplate.get(oldTopLevelTemplate.Id).Id;

        update as user newMaster;

        //Make sure to parent the new templates.
        updateNewTemplateParents(newName);

        createTemplateSteps();
        createStepDependencies();

        return newMaster.Task_Template__c;
    }

    private void loadTemplateData(String templateId) {
        //First make the new Master Template
        newMaster = new Master_Task_Template__c();
        insert as user newMaster;

        Task_Template__c currentTemplate = 
            [
                SELECT Id, Master_Task_Template__c
                FROM Task_Template__c
                WHERE Id = :templateId
                WITH USER_MODE
            ];

       mapOldTemplateIdToOldTemplate = new Map<Id, Task_Template__c> (
            [
                SELECT Id, Name, 
                    Master_Task_Template__c,
                    Assigned_To_Name__c,
                    Assigned_Type__c,
                    Assignee_Id__c,
                    Case_Record_Type__c,
                    Case_Type__c,
                    Is_Active__c,
                    Templated_Object__c,
                    Parent_Template__c,
                    Record_Owner__c,
                    Level__c,
                    Templated_Name__c,
                    Is_Master_Template__c,
                    (
                        SELECT Id, Name, 
                            Step__c, 
                            Depends_On_Step__c,
                            Task_Template__c,
                            Description__c
                        FROM Task_Template_Step_Dependencies__r
                    ),
                    (
                        SELECT Id, Name, 
                            Master_Task_Template__c,
                            Assigned_To_Name__c,
                            Assigned_Type__c,
                            Assignee_Id__c,
                            Case_Record_Type__c,
                            Case_Type__c,
                            Is_Active__c,
                            Templated_Object__c,
                            Parent_Template__c,
                            Record_Owner__c,
                            Level__c,
                            Templated_Name__c
                        FROM Task_Templates__r
                    ),
                    (
                        SELECT Id, Name,
                            Activity_Type__c,
                            Assigned_To_Name__c,
                            Assigned_Type__c,
                            Assignee_Id__c,
                            Description__c,
                            Duration_In_Days__c,
                            Order__c,
                            Parent_Task_Template__c,
                            Template_Master__c,
                            Templated_Name__c
                        FROM Parent_Task_Template_Steps__r
                    )
                FROM Task_Template__c
                WHERE Master_Task_Template__c = :currentTemplate.Master_Task_Template__c
                WITH USER_MODE
                ORDER BY Level__c DESC
            ]);

        //Find the top level template
        for(Task_Template__c temp : mapOldTemplateIdToOldTemplate.values()) {
            if(temp.Is_Master_Template__c) {
                this.oldTopLevelTemplate = temp;
                break;
            }
        }
    }
    
    private void createStepDependencies() {
        for(Task_Template__c t : mapOldTemplateIdToOldTemplate.values()) {
            for(Task_Template_Step_Dependency__c d : t.Task_Template_Step_Dependencies__r) {
                Task_Template_Step_Dependency__c newDependency = createCloneOfDependency(d);
                mapOldDependencyIdToNewDependency.put(d.Id, newDependency);
            }
        }
        insert as user mapOldDependencyIdToNewDependency.values();

    }

    /**
    * @description Assigns the parent to the new templates
    * @author Brian Ezell (Simply EZ) | 07-08-2024 
    * @param newName 
    **/
    private void updateNewTemplateParents(String newName) {

        if(newName == null) {
            throw new DmlException('You must provide a new name.');
        }

        List<Task_Template__c> updateTemplates = new List<Task_Template__c>();

        for(Id tId : mapOldTemplateIdToOldTemplate.keySet()) {
            Task_Template__c oldTemplate = mapOldTemplateIdToOldTemplate.get(tId);
            Task_Template__c newTemplate = mapOldTemplateIdToNewTemplate.get(tId);
            
            if(oldTemplate.Parent_Template__c != null) {

                updateTemplates.add(new Task_Template__c (
                    Id = newTemplate.Id,
                    Parent_Template__c = mapOldTemplateIdToNewTemplate.get(oldTemplate.Parent_Template__c).Id
                ));
            } else {

                //Top level - just make sure to set the new name
                updateTemplates.add(new Task_Template__c (
                    Id = newTemplate.Id,
                    Parent_Template__c = null,
                    Name = newName
                ));
            }
        }
        update as user updateTemplates;
    }

    /**
    * @description Creates the template steps
    * @author Brian Ezell (Simply EZ) | 06-01-2024 
    **/
    private void createTemplateSteps() {
        for(Task_Template__c t : mapOldTemplateIdToOldTemplate.values()) {
            for(Task_Template_Step__c s : t.Parent_Task_Template_Steps__r) {
                Task_Template_Step__c newStep = createCloneOfOneStep(s);
                mapOldStepIdToNewStep.put(s.Id, newStep);
            }
        }
        insert as user mapOldStepIdToNewStep.values();
        
    }

    /**
    * @description Creates a new set of templates based on the old 
    * template and related objects.
    * @author Brian Ezell (SimplyEZ) | 08-13-2024 
    * @param newName 
    **/
    private void createTemplates(String newName) {
        if(newName == null) {
            throw new DmlException('You must provide a new name.');
        }
        
        //Create a copy of each template 

        for(Task_Template__c t : mapOldTemplateIdToOldTemplate.values()) {
            Task_Template__c newTemplate = createCloneOfOneTemplate(t);
            if(t.Parent_Template__c == null) {
                newTemplate.Name = newName;
            }
            mapOldTemplateIdToNewTemplate.put(t.Id, newTemplate);
        }

        insert as user mapOldTemplateIdToNewTemplate.values();

        //Establish the parent of each template
        linkNewTemplates();
    }

    
    /**
    * @description Now that the new templates are created, link them to the parent
    * @author Brian Ezell (Simply EZ) | 06-01-2024 
    **/
    private void linkNewTemplates() {

        //Go through each newly created template and link to the parent
        for(Id id : mapOldTemplateIdToOldTemplate.keySet()) {
            Task_Template__c oldTemplate = mapOldTemplateIdToOldTemplate.get(id);
            Task_Template__c newTemplate = mapOldTemplateIdToNewTemplate.get(id);
            if(oldTemplate.Parent_Template__c != null) {
                newTemplate.Parent_Template__c = mapOldTemplateIdToNewTemplate.get(oldTemplate.Parent_Template__c).Id;
            }
        }
        update as user mapOldTemplateIdToNewTemplate.values();  
    }

    /**
    * @description Creates a copy of the template
    * @author Brian Ezell (Simply EZ) | 06-01-2024 
    * @param template 
    * @return Task_Template__c 
    **/
    private Task_Template__c createCloneOfOneTemplate(Task_Template__c template) {
        Task_Template__c newTemplate = new Task_Template__c(
            Name = template.Name,
            Templated_Name__c = template.Templated_Name__c,
            Master_Task_Template__c  = newMaster.Id,
            Assigned_To_Name__c = template.Assigned_To_Name__c,
            Assigned_Type__c = template.Assigned_Type__c,
            Assignee_Id__c = template.Assignee_Id__c,
            Case_Record_Type__c = template.Case_Record_Type__c,
            Case_Type__c = template.Case_Type__c,
            Is_Active__c = true,
            Templated_Object__c = template.Templated_Object__c,
            Parent_Template__c = null,
            Record_Owner__c = template.Record_Owner__c,
            Level__c = template.Level__c
        );
        return newTemplate;
    }


    /**
    * @description Creates a copy of the step
    * @author Brian Ezell (Simply EZ) | 06-01-2024 
    * @param step 
    * @return Task_Template_Step__c 
    **/
    private Task_Template_Step__c createCloneOfOneStep(Task_Template_Step__c step) {
        String templateName = step.Name + '-Clone';

        Task_Template_Step__c newTemplateStep = new Task_Template_Step__c(
            Name = templateName.left(50),
            Activity_Type__c = step.Activity_Type__c,
            Assigned_To_Name__c = step.Assigned_To_Name__c,
            Assigned_Type__c = step.Assigned_Type__c,
            Assignee_Id__c = step.Assignee_Id__c,
            Description__c = step.Description__c,
            Duration_In_Days__c = step.Duration_In_Days__c,
            Order__c = step.Order__c,
            Parent_Task_Template__c = mapOldTemplateIdToNewTemplate.get(step.Parent_Task_Template__c).Id,
            Templated_Name__c = step.Templated_Name__c
        );
        return newTemplateStep;
    }

    /**
    * @description Creates a copy of the dependency
    * @author Brian Ezell (Simply EZ) | 06-01-2024 
    * @param dependency 
    * @return Task_Template_Step_Dependency__c 
    **/
    private Task_Template_Step_Dependency__c createCloneOfDependency(Task_Template_Step_Dependency__c dependency) {
        Task_Template_Step_Dependency__c newDependency = new Task_Template_Step_Dependency__c(
            Step__c = mapOldStepIdToNewStep.get(dependency.Step__c).Id,
            Depends_On_Step__c = mapOldStepIdToNewStep.get(dependency.Depends_On_Step__c).Id,
            Task_Template__c = mapOldTemplateIdToNewTemplate.get(dependency.Task_Template__c).Id,
            Description__c = dependency.Description__c
        );
        return newDependency;
    }
    
}