force-app/main/default/objects/Object__c/Object__c.object-meta.xml
<CustomObject>
    <description>The representation of the objects used for template creation.</description>
    <label>Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object__c/fields/Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Api_Name__c</fullName>
    <description>The api name of the object represented</description>
    <inlineHelpText>The api name of the object represented</inlineHelpText>
    <label>Api Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Templated_Object__c.field-meta.xml
<CustomField>
    <fullName>Templated_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the object that this template can be used.</description>
    <inlineHelpText>References the object that this template can be used.</inlineHelpText>
    <label>Templated Object</label>
    <referenceTo>Object__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ObjectAndHierarchyHelper.cls
public with sharing class ObjectAndHierarchyHelper {

    private Id objectTypeId;

    public ObjectAndHierarchyHelper(String objectName) {
        System.debug('Object Name = ' + objectName);
        this.objectTypeId = 
            [
                SELECT Id
                FROM Object__c
                WHERE Api_Name__c = :objectName
                WITH USER_MODE
                LIMIT 1
            ].Id;
    }

    public ObjectTemplateCollection getObjectTemplateHierarchy() {

        List<Task_Template__c> allTemplates = getAllTemplates();

        ObjectTemplateCollection collection = new ObjectTemplateCollection();

        //First, load up the top-level templates
        for(Task_Template__c t : allTemplates) {
            if(t.Parent_Template__c == null) {
                ObjectTemplateNode parentNode = new ObjectTemplateNode(t.Name, t.Id, null);
                parentNode.childTemplates = getChildNodes(t.Id, allTemplates);
                collection.templates.add(parentNode);
            }
        }

        return collection;
    }
    
    private List<Task_Template__c> getAllTemplates() {
        return 
            [
                SELECT Id, Name, Templated_Object__c, Parent_Template__c
                FROM Task_Template__c
                WHERE Templated_Object__c = :this.objectTypeId
                ORDER BY Name,
                    Parent_Template__c NULLS FIRST
            ];
    }

    private List<ObjectTemplateNode> getChildNodes(Id parentId, List<Task_Template__c> allTemplates) {
        List<ObjectTemplateNode> childNodes = new List<ObjectTemplateNode>();
        for(Task_Template__c t : allTemplates) {
            if(t.Parent_Template__c == parentId) {
                ObjectTemplateNode childNode = new ObjectTemplateNode(t.Name, t.Id, parentId);
                childNode.childTemplates = getChildNodes(t.Id, allTemplates);
                childNodes.add(childNode);
            }
        }
        return childNodes;
    }

    public class ObjectTemplateCollection {
        
        public ObjectTemplateCollection() {
            this.templates = new List<ObjectTemplateNode>();
        }

        public List<ObjectTemplateNode> templates;
    }

    public class ObjectTemplateNode {

        public ObjectTemplateNode(String name, String id, String parentId) {
            this.name = name;
            this.id = id;
            this.parentId = parentId;
            this.childTemplates = new List<ObjectTemplateNode>();
        }

        public String name;
        public String id;
        public String parentId;
        public List<ObjectTemplateNode> childTemplates;
    }

}