force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Templated_Objects__c.field-meta.xml
<CustomField>
    <fullName>Templated_Objects__c</fullName>
    <inlineHelpText>A list of objects that this template can be used with.  If custom objects are desired, their API name will need to be added to the picklist values.</inlineHelpText>
    <label>Templated Objects</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WelcomeController.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
public with sharing class WelcomeController {

    /**
    * @description Gets a list of picklist labels/values for the Templated_Objects__c field on Task_Template__c
    * @author Brian Ezell (Simply EZ) | 09-03-2024 
    * @return String 
    **/
    @AuraEnabled
    public static String getPicklistObjects() {
        try {
            List<Schema.PicklistEntry> picklistValues = CommonFunctions.getPicklistValues('Task_Template__c', 'Templated_Objects__c');
            return JSON.serialize(picklistValues);
        } catch (Exception e) {
            throw new AuraHandledException(CommonFunctions.getExceptionError(e));
        }
    }

}