force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Export__c/Template_Export__c.object-meta.xml
<CustomObject>
    <label>Template Export</label>
    <nameField>
        <displayFormat>EXP-{0000}</displayFormat>
        <label>Template Export Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Export__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Task Template</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This must be the top level template.</errorMessage>
        <filterItems>
            <field>Task_Template__c.Is_Master_Template__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Task_Template__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Template Exports</relationshipLabel>
    <relationshipName>Template_Exports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExportTemplateControllerTest.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
@IsTest
private class ExportTemplateControllerTest {

    @IsTest
    private static void testExportTemplate() {

        User admin = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);

        System.runAs(admin) {
            TestDataFactory.TestDataFactoryData testData = TestDataFactory.createAllTestData('Contact');

            Task_Template__c template = 
                [
                    SELECT Id
                    FROM Task_Template__c
                    LIMIT 1
                ];

                ExportTemplateController.ExportTemplateRequest request = new ExportTemplateController.ExportTemplateRequest();
                request.templateId = template.Id;
                
                String responseJson = ExportTemplateController.exportTemplate(JSON.serialize(request));
                ExportTemplateController.ExportTemplateResponse response = (ExportTemplateController.ExportTemplateResponse)JSON.deserialize(responseJson, ExportTemplateController.ExportTemplateResponse.class);
                Assert.areNotEqual(null, response.exportTemplateId, 'Response should not be null.');

                Template_Export__c exportTemplate = 
                    [
                        SELECT Id
                        FROM  Template_Export__c
                    ];

                Assert.areNotEqual(null, exportTemplate, 'There should be an export template');
                Assert.areNotEqual(0, [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :response.exportTemplateId].size(), 'There should be a file on this object');
        }

    }

}