force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step_Dependency__c/Task_Template_Step_Dependency__c.object-meta.xml
<CustomObject>
    <label>Task Template Step Dependency</label>
    <nameField>
        <displayFormat>StepDependency-{0000}</displayFormat>
        <label>Task Template Step Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Template Step Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TemplateBuilderControllerTest.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 06-16-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
@IsTest
private class TemplateBuilderControllerTest {

    @IsTest
    private static void testFlowDependencies() {

        User adminUser = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);
        System.runAs(adminUser) {
            TestDataFactory.TestDataFactoryData testData = TestDataFactory.createAllTestData('Contact');
            String response = TemplateBuilderController.flowDependencies(testData.thisTemplate.Id.toString());
            List<TemplateBuilderController.TaskTemplateNode> templateNodes = (List<TemplateBuilderController.TaskTemplateNode>) JSON.deserialize(response, List<TemplateBuilderController.TaskTemplateNode>.class);
            Assert.isNotNull(templateNodes, 'Expected response to not be null');
        }

    }

    @IsTest
    private static void testDeleteTaskRecord() {

        User adminUser = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);
        System.runAs(adminUser) {
            TestDataFactory.TestDataFactoryData testData = TestDataFactory.createAllTestData('Contact');
            String response = TemplateBuilderController.flowDependencies(testData.thisTemplate.Id.toString());

            Task_Template_Step__c step =
                [
                    SELECT Id
                    FROM Task_Template_Step__c
                    LIMIT 1
                ];

            List<Task_Template_Step_Dependency__c> depends = [SELECT Id FROM Task_Template_Step_Dependency__c];
            delete depends;
            
            TemplateBuilderController.deleteTaskRecord(step.Id.toString());

            Assert.isTrue([SELECT Id FROM Task_Template_Step__c WHERE Id = :step.Id].isEmpty(), 'Step should be deleted.');
        } 

    }

    @IsTest
    private static void testDeleteTemplateRecord() {

        User adminUser = TestDataFactory.createUserWithPermissionSets(TestDataFactory.SIMPLY_TASKS_ADMIN_PERMISSION_SET, Constants.SYSTEM_ADMIN_PROFILE_NAME);
        System.runAs(adminUser) {
            TestDataFactory.TestDataFactoryData testData = TestDataFactory.createAllTestData('Contact');
            String response = TemplateBuilderController.flowDependencies(testData.thisTemplate.Id.toString());

            Task_Template__c template =
                [
                    SELECT Id
                    FROM Task_Template__c
                    LIMIT 1
                ];

            List<Task_Template_Step_Dependency__c> depends = [SELECT Id FROM Task_Template_Step_Dependency__c];
            delete depends;
                
            TemplateBuilderController.deleteTemplateRecord(template.Id.toString());

            Assert.isTrue([SELECT Id FROM Task_Template__c WHERE Id = :template.Id].isEmpty(), 'Template should be deleted.');
        }
    }

}