force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>false</active>
    <description>Used to create a task on objects</description>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <defaultValue>&quot;Task&quot;</defaultValue>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Activity_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Parent_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Task_Template__c</fullName>
    <label>Parent Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Steps (Parent Task Template)</relationshipLabel>
    <relationshipName>Parent_Task_Template_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/Task_Template_Step_Dependency__c.object-meta.xml
<CustomObject>
    <label>Task Template Step Dependency</label>
    <nameField>
        <displayFormat>StepDependency-{0000}</displayFormat>
        <label>Task Template Step Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Template Step Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Depends_On_Step__c.field-meta.xml
<CustomField>
    <fullName>Depends_On_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Depends On Step</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Task_Template_Step__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Step__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies (Depends On Step)</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Activity_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Task</fullName>
        <default>true</default>
        <label>Task</label>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <description>For Simply Tasks - used to determine the type of the activity.</description>
    <masterLabel>Activity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TaskTrackerController.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 09-18-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
public with sharing class TaskTrackerController {

    public String mermaidFlow {get;set;}

    private List<Task_Template__c> allTemplates;
    private Set<String> allIds = new Set<String>();
    private String currentId;
    //ApexPages.StandardController controller

    public TaskTrackerController() {
        currentId = ApexPages.currentPage()?.getParameters()?.get('id');
        mermaidFlow  = '---\n' + 
            'config:\n' +
            ' layout: elk\n' +
            '---\n' +
            'graph TB\n' + getMermaidForTemplate(currentId);
    }

    public String getThisUrl() {
        return String.format('{0}&fullPages={1}&id={2}', new List<String>{
            ApexPages.currentPage().getUrl().escapeHtml4(),
            ApexPages.currentPage()?.getParameters()?.get('fullPages') == 'true' ? 'false' : 'true',
            currentId
        });
    }

    public String getFullPageCss() {
        return String.format('{0}&fullPages={1}&id={2}', new List<String>{
            ApexPages.currentPage().getUrl().escapeHtml4(),
            ApexPages.currentPage()?.getParameters()?.get('fullPages') == 'true' ? 'true' : 'hidden',
            currentId
        });
    }

    public Boolean getFullScreen() {
        Boolean fullScreenCheck = ApexPages.currentPage()?.getParameters()?.get('fullPages') == 'true';
        return fullScreenCheck;
    }

    public String getMermaidForTemplate(String id) {

        //Get all assoicated templates
        allTemplates = CommonFunctions.getAllTemplates(id);

        //Get the top level master template, then work
        //downwards
        Task_Template__c masterTemplate;
        for(Task_Template__c t : allTemplates) {
            if(t.Parent_Template__c == null) {
                masterTemplate = t;
                allIds.add(t.Id);
                break;
            }
        }
        List<String> flowList = new List<String>();
        if(masterTemplate != null) {
            flowList.addAll(getTemplateFlow(masterTemplate));
        }
        
        for(Task_Template__c t : allTemplates) {
            for(Task_Template_Step_Dependency__c d : t.Task_Template_Step_Dependencies__r) {
                flowList.add(d.Depends_On_Step__c + '-.->' + d.Step__c);
            }
        }
        
        //Add the class/colors
        for(String color : Constants.MERMAID_COLORS) {
            flowList.add(color);
        }
        /*
        for(String thisId : allIds) {
            flowList.add(String.format('click {0} "{1}" "Open in New Window" _blank', new List<String>{
                thisId,
                '../' + thisId
            }));
        }
        */

        String returnString = String.join(flowList, '\n\r');
        return returnString;
    }

    private List<String> getTemplateFlow(Task_Template__c currentTemplate) {

        List<String> flowSteps = new List<String>();
     
        List<Task_Template__c> childTemplates = new List<Task_Template__c>();

        allIds.add(currentTemplate.Id);
        for(Task_Template__c t : allTemplates) {
            if(t?.Parent_Template__c == currentTemplate?.Id) {
                childTemplates.add(t);
                allIds.add(t.Id);
            }
        }

        String currentTemplateName = CommonFunctions.makeMermaidSafe(currentTemplate.Name);
        flowSteps.add(currentTemplate.Id + ':::' + Constants.MERMAID_MAIN_COLOR);
        flowSteps.add('subgraph ' +  currentTemplate.Id + '["' + currentTemplateName +'"]');

        for(Task_Template__c t : childTemplates) {
            flowSteps.addAll(getTemplateFlow(t));
        }

        flowSteps.addAll(getTemplateStepsFlow(currentTemplate));
        flowSteps.add('end');

        return flowSteps;
    }

    private List<String> getTemplateStepsFlow(Task_Template__c template) {
        List<String> flowSteps = new List<String>();
        for(Task_Template_Step__c step : template.Parent_Task_Template_Steps__r) {

            allIds.add(step.Id);
            String imageHtml = '';
            if(step.Activity_Type__c == 'Task') {
                imageHtml = CommonFunctions.getImageTag(Constants.TASK_ICON_URL);
                flowSteps.add(step.Id + ':::' + Constants.MERMAID_TASK_COLOR);
            } else {
                imageHtml = CommonFunctions.getImageTag(Constants.EVENT_ICON_URL);
                flowSteps.add(step.Id + ':::' + Constants.MERMAID_EVENT_COLOR);
            }
            flowSteps.add(step.Id + '(' + CommonFunctions.makeMermaidSafe(step.Name) + imageHtml +')');
        }
        return flowSteps;
    }
}