force-app/main/default/objects/Activity/fields/Dependent_Tasks_To_Complete__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Tasks_To_Complete__c</fullName>
    <description>Number of tasks excepted to be completed before this task can be started.</description>
    <label>Dependent Tasks To Complete</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Is_Simply_Tasks_Created__c.field-meta.xml
<CustomField>
    <fullName>Is_Simply_Tasks_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tells if Simply Tasks created this task.</inlineHelpText>
    <label>Is Simply Tasks Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Task_Template_Step__c.field-meta.xml
<CustomField>
    <fullName>Task_Template_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>The depth of this case to the master case.  Used to calculate the number of tasks and tasks completed.</description>
    <label>Level</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Master_Case__c.field-meta.xml
<CustomField>
    <fullName>Master_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The top level parent case lookup record</description>
    <label>Master Case</label>
    <referenceTo>Master_Case__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Number_of_Tasks_Completed__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tasks_Completed__c</fullName>
    <label>Number of Tasks Completed</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Number_of_Tasks_To_Complete__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tasks_To_Complete__c</fullName>
    <label>Number of Tasks To Complete</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Task_Template_Step__c.field-meta.xml
<CustomField>
    <fullName>Task_Template_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Case__c/Master_Case__c.object-meta.xml
<CustomObject>
    <label>Master Case</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Master Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Case__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Master Cases</relationshipLabel>
    <relationshipName>Master_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Task_Template__c/Master_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Master Task Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Master Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Task_Template__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A link to the master template.</description>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Master Task Templates</relationshipLabel>
    <relationshipName>Master_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/Task_Dependency__c.object-meta.xml
<CustomObject>
    <description>Houses dependencies between actual tasks.  Based on the templates, template steps, and template step dependencies.</description>
    <label>Task Dependency</label>
    <nameField>
        <label>Task Dependency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Dependency__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Task Dependencies</relationshipLabel>
    <relationshipName>Task_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/fields/Task_Depends_On_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Depends_On_Id__c</fullName>
    <label>Task Depends On Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Dependency__c/fields/Task_Template_Step__c.field-meta.xml
<CustomField>
    <fullName>Task_Template_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template Step</label>
    <referenceTo>Task_Template_Step_Dependency__c</referenceTo>
    <relationshipLabel>Task Dependencies</relationshipLabel>
    <relationshipName>Task_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Assigned_Type__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Type__c</fullName>
    <label>Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assign_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Assignee_Id__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Id__c</fullName>
    <description>The ID of the user, queue, etc that the user is assigned to.  This is handled by a lightning component.</description>
    <label>Assignee Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Is_Master_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Master_Template__c</fullName>
    <formula>ISBLANK( Parent_Template__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Master Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>The level depth of this case relative to the master template.</description>
    <label>Level</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template</relationshipLabel>
    <relationshipName>Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Templated_Name__c.field-meta.xml
<CustomField>
    <fullName>Templated_Name__c</fullName>
    <inlineHelpText>Allows templating names of cases/tasks.  Can include &quot;[Name]&quot; to insert the name of the targeted object.</inlineHelpText>
    <label>Templated Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Total_Number_Of_Steps__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_Of_Steps__c</fullName>
    <formula>Number_Of_Child_Template_Steps__c +   Number_of_Child_Steps__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Number Of Steps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>false</active>
    <description>Used to create a task on objects</description>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/Task_Template_Step__c/Task_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Task Template Step</label>
    <nameField>
        <label>Task Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <defaultValue>&quot;Task&quot;</defaultValue>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Activity_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Assigned_Type__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Type__c</fullName>
    <inlineHelpText>Who does this activity get assigned to upon creation?</inlineHelpText>
    <label>Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assign_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Assignee_Id__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Id__c</fullName>
    <description>The ID of the assigned user, queue, etc. that is used.  A lightning component fills this in.</description>
    <label>Assignee Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Duration_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Days__c</fullName>
    <label>Duration In Days</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The order of the steps when displayed under the template.</inlineHelpText>
    <label>Order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Parent_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Task_Template__c</fullName>
    <label>Parent Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Steps (Parent Task Template)</relationshipLabel>
    <relationshipName>Parent_Task_Template_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step__c/fields/Templated_Name__c.field-meta.xml
<CustomField>
    <fullName>Templated_Name__c</fullName>
    <inlineHelpText>Used as a template for the task/event name.  Can include [Name] for object name and [StepOrder] for step order fields to be included in the activity name at creation.</inlineHelpText>
    <label>Templated Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/Task_Template_Step_Dependency__c.object-meta.xml
<CustomObject>
    <label>Task Template Step Dependency</label>
    <nameField>
        <displayFormat>StepDependency-{0000}</displayFormat>
        <label>Task Template Step Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Template Step Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Depends_On_Step__c.field-meta.xml
<CustomField>
    <fullName>Depends_On_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Depends On Step</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Task_Template_Step__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Step__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies (Depends On Step)</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Step</label>
    <referenceTo>Task_Template_Step__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template_Step_Dependency__c/fields/Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>Task_Template__c</referenceTo>
    <relationshipLabel>Task Template Step Dependencies</relationshipLabel>
    <relationshipName>Task_Template_Step_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Activity_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Task</fullName>
        <default>true</default>
        <label>Task</label>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <description>For Simply Tasks - used to determine the type of the activity.</description>
    <masterLabel>Activity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Assign_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Specific User</fullName>
    </customValue>
    <customValue>
        <fullName>Queue</fullName>
    </customValue>
    <customValue>
        <fullName>Person Creating</fullName>
    </customValue>
    <customValue>
        <fullName>Case Owner</fullName>
    </customValue>
    <description>For Simply Tasks.  Defines how the object gets assigned its owner.</description>
    <masterLabel>Assign Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateProcessHelper.cls
/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 08-12-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/
public with sharing class CreateProcessHelper {

    //Allows for different versions of this request to be passed in.  The one allows for just certain templates
    //to be selected, and the other is everything under the master template.
    private CreateCaseRequestBase request;

    private Map<Id, Task_Template__c> mapTemplateIdToTemplate = new Map<Id, Task_Template__c>();
    private Map<Id, Case> mapAllTemplateIdsToCases = new Map<Id, Case>();
    private Map<Id, SObject> mapTemplateStepIdToStep = new Map<Id, SObject>();
    private Map<Id, Integer> mapStepIdToDependencyCount = new Map<Id, Integer>();

    private Master_Case__c masterCase;
    private Case topLevelCase;
    private SObject currentObject;
    private String objectApiName;
    private String objectName;
    private Task_Template__c topLevelTemplate;

    /**
    * @description Setup the data for creating the cases from the templates
    * @author Brian Ezell (Simply EZ) | 07-24-2024 
    **/
    public CreateProcessHelper(CreateCaseRequestBase request) {
        this.request = request;
        this.currentObject = request.getSObject();
        this.objectApiName = request.objectApiName;
        String mainFieldName = CommonFunctions.getObjectMainField(request.objectApiName);

        System.debug(this.currentObject);

        this.objectName = this.currentObject.get(mainFieldName) == null ? '' : this.currentObject.get(mainFieldName).toString();
        mapTemplateIdToTemplate = request.getTemplatesMap();

        //Figure out which template is the top of the chain
        for(Task_Template__c template : mapTemplateIdToTemplate.values()) {
            if(template.Is_Master_Template__c) {
                this.topLevelTemplate = template;
                break;
            }
        }
        
        mapAllTemplateIdsToCases = new Map<Id, Case>();
        mapTemplateStepIdToStep = new Map<Id, SObject>();

        loadTemplateMap();
        createDependencyCounts();
    }

    /**
    * @description Creates the cases/tasks/events from the template and template steps
    * @author Brian Ezell (Simply EZ) | 07-24-2024 
    **/
    public void createCases() {
        createMasterCase();
        createCasesFromTemplates();
        updateCaseParents();
        createCaseSteps();
        createStepDependencies();
    }

    /**
    * @description Gets the top level case id
    * @author Brian Ezell (Simply EZ) | 10-03-2024 
    * @return Id 
    **/
    public Id getTopLevelCaseId() {
        return this.topLevelCase.Id;
    }

    /**
    * @description Gets the id of the master case object
    * @author Brian Ezell (Simply EZ) | 10-03-2024 
    * @return Id 
    **/
    public Id getMasterCaseId() {
        return this.masterCase.Id;
    }


    /**
    * @description Used in constructor:
    *   Loads up a map of template ids and step ids to corresponding maps.
    * @author Brian Ezell (Simply EZ) | 07-29-2024 
    **/
    private void loadTemplateMap() {
        //Load up the template maps
        for(Task_Template__c template : mapTemplateIdToTemplate.values()) {
            for(Task_Template_Step__c step : template.Parent_Task_Template_Steps__r) {
                mapTemplateStepIdToStep.put(step.Id, null);
                mapStepIdToDependencyCount.put(step.Id, 0);
            }
        }
    }

    /**
    * @description Creates a map of step dependencies.  Assumed mapStepIdToDependencyCount has been populated.
    * @author Brian Ezell (Simply EZ) | 07-29-2024 
    **/
    private void createDependencyCounts() {
        List<AggregateResult> dependencyCounts = 
            [
                SELECT Step__c, COUNT(Depends_On_Step__c) DependentCount
                FROM Task_Template_Step_Dependency__c
                WHERE Step__c = :this.mapStepIdToDependencyCount.keySet()
                WITH SYSTEM_MODE
                GROUP BY Step__c
            ];
        for(AggregateResult dep : dependencyCounts) {
            Id stepId = Id.valueOf(dep.get('Step__c')?.toString());
            this.mapStepIdToDependencyCount.put(stepId, Integer.valueOf(dep.get('DependentCount').toString()));
        }
    }

    /**
    * @description Add step dependencies between case tasks
    * @author Brian Ezell (Simply EZ) | 07-29-2024 
    **/
    private void createStepDependencies() {

        List<Task_Dependency__c> newDependencies = new List<Task_Dependency__c>();

        for(Task_Template__c template : mapTemplateIdToTemplate.values()) {
            Case c = this.mapAllTemplateIdsToCases.get(template.Id);

            for(Task_Template_Step_Dependency__c dep : template.Task_Template_Step_Dependencies__r) {

                Id taskId = this.mapTemplateStepIdToStep.get(dep.Step__c).Id;
                Id dependsOnTaskId = this.mapTemplateStepIdToStep.get(dep.Depends_On_Step__c).Id;

                Task_Dependency__c newDependency = new Task_Dependency__c (
                    Case__c = c.Id,
                    Task_Template_Step__c = dep.Id,
                    Task_Depends_On_Id__c = dependsOnTaskId,
                    Task_Id__c = taskId
                );
                newDependencies.add(newDependency);
            }
        }

        insert as user newDependencies;
    }

    /**
    * @description Creates the steps for the templates to cases
    * @author Brian Ezell (Simply EZ) | 07-29-2024 
    **/
    private void createCaseSteps() {

        List<Task> newTasks = new List<Task>();
        List<Event> newEvents = new List<Event>();

        for(Task_Template__c template : mapTemplateIdToTemplate.values()) {
            Id caseId = mapAllTemplateIdsToCases.get(template.Id).Id;
            for(Task_Template_Step__c step : template.Parent_Task_Template_Steps__r) {
                SObject newTemplateStep = createStep(step, caseId, template);
                this.mapTemplateStepIdToStep.put(step.Id, newTemplateStep);

                if(newTemplateStep.getSObjectType().getDescribe().getName() == 'Task') {
                    newTasks.add((Task)newTemplateStep);
                } else {
                    newEvents.add((Event)newTemplateStep);
                }
            }
        }

        addTasks(newTasks);
        addEvents(newEvents);
    }

    /**
    * @description Adds new tasks to system.  Checks in place for security and size
    * @author Brian Ezell (Simply EZ) | 08-07-2025 
    * @param newTasks 
    **/
    private void addTasks(List<Task> newTasks) {
        if(newTasks.size() > 0) {
            insert as user newTasks;
        }
    }

    /**
    * @description Adds new events to system.  Checks in place for security and size
    * @author Brian Ezell (Simply EZ) | 08-07-2025 
    * @param newEvents 
    **/
    private void addEvents(List<Event> newEvents) {
        if(newEvents.size() > 0) {
            insert as user newEvents;
        }
    }

    /**
    * @description Creates an SObject step from the task template step object
    * @author Brian Ezell (Simply EZ) | 10-03-2024 
    * @param step 
    * @param caseId 
    * @param template 
    * @return SObject 
    **/
    private SObject createStep(Task_Template_Step__c step, Id caseId, Task_Template__c template) {
        
        //The dependency count is used to count down the number of
        //dependent tasks this task is waiting on.  When it gets to 0
        //then this task gets set to "Not Started" and the Activity
        //Date is set from that point.
        Integer dependentCount = mapStepIdToDependencyCount.get(step.Id);
        String taskSubject = step.Templated_Name__c == null ? step.Name :
        step.Templated_Name__c?.Replace('[Name]', this.objectName)?.Replace('[StepOrder]',
        step.Order__c == null ? 
            '' : 
            string.valueOf(step.Order__c));

        if(step.Activity_Type__c == 'Task') {
            return new Task(
                ActivityDate = dependentCount > 0 ? null :
                    step.Duration_In_Days__c == null ? null :
                    Date.today() + (Integer)step.Duration_In_Days__c,
                OwnerId = getOwnerIdFromTemplateStep(step, template, this.currentObject),
                WhatId = caseId,
                Is_Simply_Tasks_Created__c = true,
                Subject = taskSubject,
                Task_Template_Step__c = step.Id,
                Dependent_Tasks_To_Complete__c = dependentCount,
                Status = dependentCount == 0 ? 
                    Constants.TASK_START_STATUS : 
                    Constants.TASK_PENDING_STATUS
            );
        } else {
            return new Event(
                ActivityDate = //dependentCount > 0 ? Date.today() :
                    step.Duration_In_Days__c == null ? Date.today() :
                    Date.today() + (Integer)step.Duration_In_Days__c,
                OwnerId = getOwnerIdFromTemplateStep(step, template, this.currentObject),
                WhatId = caseId,
                Is_Simply_Tasks_Created__c = true,
                Subject = taskSubject,
                Task_Template_Step__c = step.Id,
                Dependent_Tasks_To_Complete__c = dependentCount,
                Type = 'Meeting',
                IsAllDayEvent = true
            );
        }
    }


    /**
    * @description Fills in the mapAllTemplateIdsToCases with the new cases. 
    * @author Brian Ezell (Simply EZ) | 07-29-2024 
    **/
    private void createCasesFromTemplates() {

        String mainFieldName = CommonFunctions.getObjectMainField(objectApiName);
        String objectRecordName = String.valueOf(this.currentObject?.get(mainFieldName));

        for(Task_Template__c template : mapTemplateIdToTemplate.values()) {

            //Allow templating names for dynamic creation
            String caseTemplatedName = 
                template.Templated_Name__c == null ?
                template.Name : 
                template.Templated_Name__c.replace('[Name]', objectRecordName);

            Case newCase = new Case (
                Task_Template__c = template.Id,
                ContactId = this.request.objectApiName == 'Contact' ? this.currentObject.Id : null,
                AccountId = this.request.objectApiName == 'Account' ? this.currentObject.Id :
                    this.request.objectApiName == 'Opportunity' ? 
                        String.valueOf(this.currentObject.get('AccountId')) :
                        null,
                OwnerId = getOwnerIdFromTemplate(template, this.currentObject),
                Number_of_Tasks_To_Complete__c = template.Total_Number_Of_Steps__c,
                Number_of_Tasks_Completed__c = 0,
                Subject = caseTemplatedName,
                Master_Case__c = masterCase.Id,
                RecordTypeId = Constants.SIMPLY_TASK_CASE_RECORD_TYPE_ID,
                Level__c = template.Level__c
            );
            this.mapAllTemplateIdsToCases.put(template.Id, newCase);
        }


        addCases(this.mapAllTemplateIdsToCases.values());

        this.topLevelCase = mapAllTemplateIdsToCases.get(this.topLevelTemplate.Id);
        this.masterCase.Case__c = this.topLevelCase.Id;
        update as user this.masterCase;
    }


    /**
    * @description 
    * @author Brian Ezell (Simply EZ) | 08-07-2025 
    * @param newCases 
    **/
    private void addCases(List<Case> newCases) {
        if(newCases.size() > 0) {
            insert as user newCases;
        }
    }

    /**
    * @description Update the parent case ids
    * @author Brian Ezell (Simply EZ) | 07-30-2024 
    **/
    private void updateCaseParents() {

        Integer count = 0;

        for(Task_Template__c template : mapTemplateIdToTemplate.values()) {
            
            //If it has a parent, lookup the parent template
            if(template.Parent_Template__c != null) {
                Case parentCase = this.mapAllTemplateIdsToCases.get(template.Parent_Template__c);
                this.mapAllTemplateIdsToCases.get(template.Id).ParentId = parentCase.Id;
                count++;
            }
        }
        
        update as user this.mapAllTemplateIdsToCases.values();
    
    }


    /**
    * @description Generates the master case objects mapped from the template ids
    * @author Brian Ezell (Simply EZ) | 07-24-2024 
    **/
    private void createMasterCase() {
        Master_Case__c newMasterCase = new Master_Case__c();
        insert as user newMasterCase;
        this.masterCase = newMasterCase;
    }
    
   /**
   * @description Returns who the owner should be based on the template
   * @author Brian Ezell (Simply EZ) | 07-29-2024 
   * @param template 
   * @param targetObject 
   * @return Id 
   **/
   private static Id getOwnerIdFromTemplate(Task_Template__c template, SObject targetObject) {

        if(template.Assigned_Type__c == 'Object Owner') {
            return (Id)(targetObject.get('OwnerId'));
        }

        if(template.Assigned_Type__c == 'Specific User' && template.Assignee_Id__c != null) {
            return template.Assignee_Id__c;
        }

        return UserInfo.getUserId();
    }

    /**
    * @description Returns the owner from the template step.
    * @author Brian Ezell (Simply EZ) | 07-29-2024 
    * @param step 
    * @param template 
    * @param targetObject 
    * @return Id 
    **/
    private static Id getOwnerIdFromTemplateStep(Task_Template_Step__c step, Task_Template__c template, SObject targetObject) {
        if(step.Assigned_Type__c == 'Specific User' && step.Assignee_Id__c != null) {
            return step.Assignee_Id__c;
        }

        if(step.Assigned_Type__c == 'Case Owner') {
            return getOwnerIdFromTemplate(template, targetObject);
        }

        return UserInfo.getUserId();
    }

    public virtual class CreateCaseRequestBase {
        public String objectApiName;
        public String objectId;
        public String templateId;

       /**
       * @description Gets the SObject associated with this request
       * @author Brian Ezell (Simply EZ) | 07-24-2024 
       * @return SObject 
       **/
       public virtual SObject getSObject() {

            List<SObject> objList = new List<SObject>();
            Id thisId = objectId;
            List<String> mainFields = CommonFunctions.getObjectMainFieldList(objectApiName);
            String fieldsToQuery = String.join(mainFields, ', ');
            String sql = String.format('SELECT {0} FROM {1} WHERE Id = :objectId WITH USER_MODE',
                new List<String> {
                    fieldsToQuery,
                    objectApiName
                });

            objList = Database.query(String.escapeSingleQuotes(sql));
            return objList.size() == 0 ? null : objList[0];
        }

        public virtual Map<Id, Task_Template__c> getTemplatesMap() {
            return new Map<Id, Task_Template__c>();
        }

    }


    //Creates an container for creating a task template case list from a template and object
    public class CreateCaseRequest extends CreateCaseRequestBase {

        /**
        * @description Gets a map of the template Id to the template all associated with the templates
        *   used with this template.
        * @author Brian Ezell (Simply EZ) | 07-24-2024 
        * @return Map<Id, Task_Template__c> 
        **/
        public override Map<Id, Task_Template__c> getTemplatesMap() {

            System.debug('***STARTING CreateCaseRequest.getTemplatesMap***');
            System.debug('This =  ' + this);
            System.debug('templateId = ' + templateId);
            System.debug('objectApiName = ' + objectApiName);   

            Task_Template__c template = 
                [
                    SELECT Id, Master_Task_Template__c
                    FROM Task_Template__c
                    WHERE Id = :templateId
                    WITH USER_MODE
                ];

            return
                new Map<Id, Task_Template__c> (
                [
                    SELECT Id, Name, Is_Active__c, Total_Number_Of_Steps__c, Parent_Template__r.Name, 
                        Templated_Name__c, Is_Master_Template__c, Parent_Template__c,
                        Assignee_Id__c, Assigned_Type__c, Level__c,
                        (
                            SELECT Id, Name, Description__c, Assignee_Id__c, Assigned_Type__c,
                                Templated_Name__c, Duration_In_Days__c, Order__c, 
                                Activity_Type__c
                            FROM Parent_Task_Template_Steps__r
                            ORDER BY Order__c, Templated_Name__c
                        ),
                        (
                            SELECT Id, Depends_On_Step__c, Step__c, Task_Template__c
                            FROM Task_Template_Step_Dependencies__r
                        )
                    FROM Task_Template__c
                    WHERE Master_Task_Template__c = :template.Master_Task_Template__c
                        AND Is_Active__c = true
                    WITH USER_MODE
                ]);
        }

    }


    //Creates an container for creating a task template case list from a template and object
    public class CreateCaseWithHierarchyRequest extends CreateCaseRequestBase {
        public List<Id> selectedTemplateIds;

        /**
        * @description Gets a map of the template Id to the template all associated with the templates
        *   used with this template.
        * @author Brian Ezell (Simply EZ) | 07-24-2024 
        * @return Map<Id, Task_Template__c> 
        **/
        public override Map<Id, Task_Template__c> getTemplatesMap() {

            System.debug('***STARTING CreateCaseWithHierarchyRequest.getTemplatesMap***');
            System.debug('This =  ' + this);
            System.debug('templateId = ' + templateId);
            System.debug('objectApiName = ' + objectApiName);  


            Task_Template__c template = 
                [
                    SELECT Id, Master_Task_Template__c
                    FROM Task_Template__c
                    WHERE Id = :selectedTemplateIds
                    WITH USER_MODE
                    LIMIT 1
                ];

            return
                new Map<Id, Task_Template__c> (
                [
                    SELECT Id, Name, Is_Active__c, Total_Number_Of_Steps__c, Parent_Template__r.Name, 
                        Templated_Name__c, Is_Master_Template__c, Parent_Template__c,
                        Assignee_Id__c, Assigned_Type__c, Level__c,
                        (
                            SELECT Id, Name, Description__c, Assignee_Id__c, Assigned_Type__c,
                                Templated_Name__c, Duration_In_Days__c, Order__c, 
                                Activity_Type__c
                            FROM Parent_Task_Template_Steps__r
                            ORDER BY Order__c, Templated_Name__c
                        ),
                        (
                            SELECT Id, Depends_On_Step__c, Step__c, Task_Template__c
                            FROM Task_Template_Step_Dependencies__r
                        )
                    FROM Task_Template__c
                    WHERE Master_Task_Template__c = :template.Master_Task_Template__c
                        AND Id IN :selectedTemplateIds
                        AND Is_Active__c = true
                    WITH USER_MODE
                ]);
        }

    }


}